project_identifier_env: CROWDIN_DOCUSAURUS_PROJECT_ID
api_key_env: CROWDIN_DOCUSAURUS_API_KEY
base_path: "./"
preserve_hierarchy: true

files:
  -
    source: '/docs/**/*.md'
    translation: '/website-1.x/translated_docs/%locale%/**/%original_file_name%'
    languages_mapping: &anchor
      locale:
        'zh-CN': 'zh-CN'
        'fr': 'fr'
        'ko': 'ko'
        'ru': 'ru'
        'pt-BR': 'pt-BR'
  -
    source: '/website-1.x/versioned_docs/**/*.md'
    translation: '/website-1.x/translated_docs/%locale%/**/%original_file_name%'
    languages_mapping: *anchor
  -
    source: '/website-1.x/i18n/en.json'
    translation: '/website-1.x/i18n/%locale%.json'
    languages_mapping: *anchor
